// layout.tsx
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './global.css';

const suit = localFont({
	src: './fonts/SUIT-Variable.woff2',
	// CSS 변수로(--font-suit)
	variable: '--font-suit',
	display: 'swap',
});

const pretendard = localFont({
	src: './fonts/PretendardVariable.woff2',
	// CSS 변수로(--font-pretendard)
	variable: '--font-pretendard',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		// html 태그에 두 CSS 변수를 모두 포함
		<html lang='en' className={`${suit.variable} ${pretendard.variable}`}>
			<body className={suit.className}>{children}</body>
		</html>
	);
}
